//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaDS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionRolesOpciones
    {
        public int ID_AsignacionRol { get; set; }
        public int ID_Rol { get; set; }
        public int ID_Opcion { get; set; }
    
        public virtual Opciones Opciones { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
