//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaDS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones
    {
        public int ID_Calificacion { get; set; }
        public int ID_Materia { get; set; }
        public int NIE { get; set; }
        public int ID_Docente { get; set; }
        public Nullable<decimal> Examen1 { get; set; }
        public Nullable<decimal> Examen2 { get; set; }
        public Nullable<decimal> Examen3 { get; set; }
        public Nullable<decimal> ExamenFinal { get; set; }
        public Nullable<decimal> Tareas { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public string Estado { get; set; }
    
        public virtual Docentes Docentes { get; set; }
        public virtual Materias Materias { get; set; }
        public virtual Estudiantes Estudiantes { get; set; }
    }
}
