//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscuelaDS.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupos()
        {
            this.Matriculas = new HashSet<Matriculas>();
        }
    
        public int ID_Grupo { get; set; }
        public string Grado { get; set; }
        public string Seccion { get; set; }
        public int Anio { get; set; }
        public int ID_Turno { get; set; }
        public int ID_Aula { get; set; }
        public int ID_Docente { get; set; }
    
        public virtual Aulas Aulas { get; set; }
        public virtual Docentes Docentes { get; set; }
        public virtual Turnos Turnos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matriculas> Matriculas { get; set; }
    }
}
